# Generated by Django 5.1.2 on 2024-10-19 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('user_nickname', models.CharField(default='', max_length=100, primary_key=True, serialize=False)),
                ('user_name', models.CharField(default='', max_length=160)),
                ('user_email', models.EmailField(default=0, max_length=254)),
                ('user_age', models.IntegerField(default=0)),
            ],
        ),
    ]
